### ISSUE TITLE
Roadmap do produto

### ISSUE THREAD

**Issue by JoelSRangel** [MDS-grupo-9/MDS_Project#31]
## Descrição

Criar o arquivo de roadmap do produto, com a finalidade de acompanhar todas as atividades realizadas em cada sprint feita pela equipe

## Tarefas:

- [x] Estudar o desenvolvimento de um roadmap
- [x] Criar arquivo de roadmap
- [x] Criar a documentação referente ao roadmap

## Critérios de Aceitação:

- Ter sido realizada de forma satisfatória a documentação do roadmap

**Comment by JoelSRangel** [comment]
A issue foi completada com sucesso
